# Generated by Django 5.2.7 on 2025-11-03 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('subscribers', models.IntegerField()),
                ('videos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ActorDetails',
            fields=[
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='actor.actor')),
                ('relationship', models.IntegerField(null=True)),
                ('interests', models.TextField(null=True)),
                ('gender', models.TextField(null=True)),
                ('birth_date', models.DateField(null=True)),
                ('birth_location', models.TextField(null=True)),
                ('endowment', models.IntegerField(null=True)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('ethnicity', models.TextField()),
                ('hair_color', models.TextField(null=True)),
                ('foreskin', models.TextField(null=True)),
                ('facial_hair', models.TextField(null=True)),
                ('tattoos', models.BooleanField(null=True)),
                ('piercing', models.BooleanField(null=True)),
                ('interest', models.TextField(null=True)),
                ('turns_on', models.IntegerField(null=True)),
                ('turns_off', models.IntegerField(null=True)),
            ],
        ),
    ]
