# Generated by Django 5.2.7 on 2025-11-03 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actordetails',
            name='actor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='actor.actor'),
        ),
    ]
