# Generated by Django 5.2.7 on 2025-11-03 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.TextField()),
                ('tags', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.TextField()),
                ('isMedia', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='OneWeekVideoStatics',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MediaInteraction',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='media.media')),
                ('likes', models.IntegerField()),
                ('dislikes', models.IntegerField()),
                ('views', models.IntegerField()),
            ],
        ),
    ]
