# Generated by Django 5.2.7 on 2025-11-03 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0002_alter_actordetails_actor'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='isMedia',
        ),
        migrations.RemoveField(
            model_name='media',
            name='location',
        ),
        migrations.AddField(
            model_name='media',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='actor.actor'),
        ),
        migrations.AddField(
            model_name='media',
            name='is_video',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='category',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='tags',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='mediainteraction',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='media.media'),
        ),
    ]
