# Generated by Django 5.2.8 on 2025-11-06 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_remove_media_ismedia_remove_media_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='title',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='oneweekvideostatics',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='media.media'),
        ),
    ]
