# Generated by Django 5.2.8 on 2025-11-06 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_alter_media_title_alter_oneweekvideostatics_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='media',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='media',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='media',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='media',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='MediaInteraction',
        ),
    ]
