# Generated by Django 5.2.8 on 2025-11-06 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_remove_media_updated_at_media_dislikes_media_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='length',
            field=models.IntegerField(default=0),
        ),
    ]
